server:
  port: 8453


spring:
  redis:
    database: 0
    timeout: 3000
    sentinel:
      master: mymaster
      nodes: 192.168.226.131:26379,192.268.226.131:26380
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000

  data:
    mongodb:
      uri: mongodb://wgq:wgq@192.168.226.131:27017/appdb?authSource=appdb